// Flavor lines shown on the full-screen pending view (app/page.tsx) while a
// backend round-trip is in flight — a few are picked at random and rotated
// so a slow response reads as atmosphere rather than a stall.
export const DUNGEON_FLAVOR_LINES: string[] = [
  "The goblins are adjusting the levers again.",
  "Something ancient is waking up, slowly and annoyed.",
  "The dungeon is putting on its best face.",
  "A bone pile just sighed.",
  "The torchlight is trying to remember where it was.",
  "The walls are listening. They always are.",
  "The wizard called it “stable.” This is a bad sign.",
  "The black gate is pretending not to notice you.",
  "A skeleton is rehearsing its dramatic entrance.",
  "The loading bar has been offered wine.",
  "The grave dust is settling into shape.",
  "The rogue already found a way around this.",
  "The realm is buffering with a grim little smile.",
  "The altar is accepting prayers and complaints.",
  "The monsters are stretching before the hunt.",
  "A cursed boot has nearly finished tying itself.",
  "The castle has remembered a worse day.",
  "The dungeon smells of wet stone and old mistakes.",
  "The goblin clerk is counting the wrong coins.",
  "The moon is up, and that never helps.",
  "The dead are not rising yet. They’re late.",
  "The bridge is thinking about collapse.",
  "The treasure chest is being suspiciously quiet.",
  "The corridor knows what it did.",
  "The code gremlins are fighting over a small screw.",
  "The witch is stirring something best left unnamed.",
  "The hero’s confidence is loading faster than the game.",
  "The war drum is warming up.",
  "The old shrine has taken offense.",
  "The dungeon was rebuilt from the bones of a worse dungeon.",
  "A bat has lodged itself in the network.",
  "The apothecary is labeling the poisons.",
  "The goblin king is choosing a more flattering crown.",
  "The shadow in the corner has your name on it.",
  "The trapdoor has not decided whether to cooperate.",
  "The crypt is being aired out for guests.",
  "The bard is inventing a lie about this delay.",
  "The doom is being calibrated.",
  "The tavern is filling with bad decisions.",
  "The dragon is reading the patch notes with suspicion.",
  "The priest has declared this “a test.”",
  "The rats are advancing with purpose.",
  "The old forge still remembers violence.",
  "The manuscript is missing several pages and one soul.",
  "The wall is not solid in the way you’d prefer.",
  "The dungeon chief insists this is all part of the atmosphere.",
  "The necromancer is checking the quality of the bones.",
  "The lanterns are trying to look brave.",
  "The dead corridor has become livelier than expected.",
  "The system load has entered its moody phase.",
  "A spider is already halfway through the ceiling.",
  "The black forest is waiting for a mistake.",
  "The king’s messenger arrived too late, as usual.",
  "The map is pretending to be helpful.",
  "The cursed mirror has opinions.",
  "The enemy is not here yet, which is somehow worse.",
  "The graveyard has begun whispering again.",
  "The goblin choir is warming up with terrible pitch.",
  "The ruins are full of patience and bad intent.",
  "The fight has not started, but the violence is ready.",
  "The old stones are remembering blood.",
  "The potion fizzed, then regretted existing.",
  "The loading ritual requires one more dramatic pause.",
  "The witch’s cat has judged you already.",
  "The dark water is reflecting something behind you.",
  "The dungeon doors are being rude on purpose.",
  "The crossbow trap is practicing restraint.",
  "The grave robbers were here first and left disappointed.",
  "The curse is currently consulting its notes.",
  "The monster is waiting for the perfect moment to be seen.",
  "The server goblin says “almost ready” with no shame.",
  "The chapel candles have gone out in sympathy.",
  "The crypt keeper is on his second warning.",
  "The long corridor is longer than it should be.",
  "The old map has started lying again.",
  "The warlock’s patience is thinner than the walls.",
  "The loading spell is being held together by chanting.",
  "The dungeon likes you less than it did a moment ago.",
  "The only safe path is under review.",
  "The beast is sniffing the air and finding you interesting.",
  "The tavern door has been replaced with bad news.",
  "The blood rune is almost finished arranging itself.",
  "The dungeon is hungry, and it’s not metaphorical.",
  "The torch smoke is spelling warnings.",
  "The old gods are taking attendance.",
  "The grave wind is moving something that should stay still.",
  "The armor is loading, but so is the funeral.",
  "The secret door is being secret with great effort.",
  "The rogue says this would go faster with fewer morals.",
  "The abyss is opening its notes.",
  "The castle is in a foul mood and won’t apologize.",
  "The dungeon’s teeth are showing.",
  "The goblin engineer has made an improvement. This is alarming.",
  "The night is folding itself into a more dangerous shape.",
  "The loading screen has been blessed, cursed, and inspected.",
  "The minions are ready, which is somehow the problem.",
  "The silence is not empty. It’s waiting.",
  "The realm is nearly done becoming a nightmare.",
  "The final door is close, and it knows your name.",
  "The dungeon is ready now. That may be the worst part.",
];
